# Generated by Django 5.2.1 on 2025-06-24 05:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billview', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Age',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('SIDO_SGG', models.CharField(max_length=100)),
                ('SIDO', models.CharField(max_length=100)),
                ('SGG', models.CharField(max_length=100)),
                ('SIGUNGU', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('party', models.CharField(max_length=100, unique=True)),
                ('color', models.CharField(default='#000000', max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('member_id', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=10)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('age', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geovote.age')),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='geovote.district')),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geovote.party')),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(max_length=10)),
                ('date', models.DateField()),
                ('age', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geovote.age')),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billview.bill')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geovote.member')),
            ],
        ),
    ]
