# Generated by Django 5.2.1 on 2025-05-26 05:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('title', models.CharField(max_length=200)),
                ('bill_id', models.CharField(max_length=100, unique=True)),
                ('bill_number', models.CharField(max_length=50)),
                ('content', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SGG_Code', models.CharField(max_length=100, unique=True)),
                ('SIDO_SGG', models.CharField(max_length=100, unique=True)),
                ('SIDO', models.CharField(max_length=100, unique=True)),
                ('SGG', models.CharField(max_length=100, unique=True)),
                ('boundary', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('party', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('member_id', models.CharField(max_length=50, unique=True)),
                ('gender', models.CharField(max_length=10)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geovote.district')),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geovote.party')),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote_result', models.CharField(max_length=10)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geovote.bill')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geovote.member')),
            ],
        ),
    ]
