# Generated by Django 5.2.1 on 2025-05-27 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geovote', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='district',
            name='boundary',
            field=models.JSONField(),
        ),
    ]
