# Generated by Django 5.2.1 on 2025-05-26 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geovote', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='district',
            name='SIDO',
            field=models.CharField(max_length=100),
        ),
    ]
