# Generated by Django 5.2.1 on 2025-05-29 02:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geovote', '0002_rename_bill_vote_bill_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vote',
            old_name='bill_id',
            new_name='bill_number',
        ),
    ]
