# Generated by Django 5.2.1 on 2025-05-26 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geovote', '0002_alter_district_sido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='district',
            name='SGG',
            field=models.CharField(max_length=100),
        ),
    ]
