# Generated by Django 5.2.1 on 2025-05-30 02:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geovote', '0002_rename_vote_result_vote_result'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='geovote.district'),
        ),
    ]
