# Generated by Django 5.2.1 on 2025-05-29 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geovote', '0003_rename_bill_id_vote_bill_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vote',
            old_name='bill_number',
            new_name='bill',
        ),
    ]
