# Generated by Django 5.2.1 on 2025-05-27 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geovote', '0003_alter_district_sgg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='member_id',
            field=models.CharField(max_length=50),
        ),
    ]
