# Generated by Django 5.2.1 on 2025-05-29 02:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billview', '0001_initial'),
        ('geovote', '0004_rename_bill_number_vote_bill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='bill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billview.bill'),
        ),
        migrations.DeleteModel(
            name='Bill',
        ),
    ]
