# Generated by Django 5.2.1 on 2025-06-30 00:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('billview', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='billlike',
            name='bill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billview.bill'),
        ),
        migrations.AddField(
            model_name='billlike',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='billlike',
            unique_together={('user', 'bill')},
        ),
    ]
