# Generated by Django 5.2.1 on 2025-06-30 05:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
        ('geovote', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geovote.member')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '의원 좋아요',
                'verbose_name_plural': '의원 좋아요 목록',
                'unique_together': {('user', 'member')},
            },
        ),
    ]
