# Generated by Django 5.2.1 on 2025-06-09 06:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('geovote', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgeSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_bills', models.PositiveIntegerField(default=0)),
                ('total_parties', models.PositiveIntegerField(default=0)),
                ('male_count', models.PositiveIntegerField(default=0)),
                ('female_count', models.PositiveIntegerField(default=0)),
                ('female_percent', models.FloatField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('age', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='geovote.age')),
            ],
        ),
        migrations.CreateModel(
            name='ClusterKeyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cluster_num', models.IntegerField(unique=True)),
                ('keyword_json', models.TextField(blank=True, null=True)),
                ('age', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geovote.age')),
            ],
        ),
        migrations.CreateModel(
            name='PartyClusterVoteSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cluster_num', models.IntegerField()),
                ('cluster_keyword', models.TextField(blank=True, null=True)),
                ('support_count', models.PositiveIntegerField(default=0)),
                ('oppose_count', models.PositiveIntegerField(default=0)),
                ('abstain_count', models.PositiveIntegerField(default=0)),
                ('absent_count', models.PositiveIntegerField(default=0)),
                ('total_votes', models.PositiveIntegerField(default=0)),
                ('age', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geovote.age')),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geovote.party')),
            ],
            options={
                'verbose_name': '정당-클러스터 투표 요약',
                'verbose_name_plural': '정당-클러스터 투표 요약들',
                'unique_together': {('age', 'cluster_num', 'party')},
            },
        ),
        migrations.CreateModel(
            name='PartyVoteSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_count', models.PositiveIntegerField(default=0)),
                ('support_ratio', models.FloatField(default=0)),
                ('oppose_ratio', models.FloatField(default=0)),
                ('abstain_ratio', models.FloatField(default=0)),
                ('absent_ratio', models.FloatField(default=0)),
                ('total_votes', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('age', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geovote.age')),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geovote.party')),
            ],
            options={
                'verbose_name': '정당별 표결 요약',
                'verbose_name_plural': '정당별 표결 요약들',
                'unique_together': {('age', 'party')},
            },
        ),
    ]
