# Generated by Django 5.2.1 on 2025-06-17 01:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('geovote', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgeStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_bills', models.PositiveIntegerField(default=0)),
                ('total_parties', models.PositiveIntegerField(default=0)),
                ('male_count', models.PositiveIntegerField(default=0)),
                ('female_count', models.PositiveIntegerField(default=0)),
                ('female_percent', models.FloatField(default=0)),
                ('hhi', models.FloatField(default=0.0)),
                ('enp', models.FloatField(default=0.0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('age', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='geovote.age')),
            ],
        ),
        migrations.CreateModel(
            name='ClusterKeyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cluster_num', models.IntegerField()),
                ('keyword_json', models.TextField(blank=True, null=True)),
                ('age', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geovote.age')),
            ],
        ),
        migrations.CreateModel(
            name='VoteSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_name', models.CharField(max_length=100)),
                ('cluster', models.CharField(max_length=100)),
                ('cluster_keyword', models.CharField(blank=True, max_length=255)),
                ('bill_count', models.IntegerField(default=0)),
                ('찬성', models.IntegerField(default=0)),
                ('반대', models.IntegerField(default=0)),
                ('기권', models.IntegerField(default=0)),
                ('불참', models.IntegerField(default=0)),
            ],
            options={
                'unique_together': {('member_name', 'cluster')},
            },
        ),
        migrations.CreateModel(
            name='PartyClusterStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cluster_num', models.IntegerField()),
                ('cluster_keyword', models.JSONField(blank=True, null=True)),
                ('support_ratio', models.FloatField(default=0)),
                ('oppose_ratio', models.FloatField(default=0)),
                ('abstain_ratio', models.FloatField(default=0)),
                ('absent_ratio', models.FloatField(default=0)),
                ('total_votes', models.PositiveIntegerField(default=0)),
                ('age', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geovote.age')),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geovote.party')),
            ],
            options={
                'verbose_name': '정당-클러스터 투표 요약',
                'verbose_name_plural': '정당-클러스터 투표 요약들',
                'indexes': [models.Index(fields=['age', 'cluster_num', 'party'], name='main_partyc_age_id_5186cd_idx')],
                'unique_together': {('age', 'cluster_num', 'party')},
            },
        ),
        migrations.CreateModel(
            name='PartyConcentration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.PositiveSmallIntegerField()),
                ('member_count', models.PositiveIntegerField(default=0)),
                ('vote_support_ratio', models.FloatField(default=0.0)),
                ('seat_share', models.FloatField(default=0)),
                ('age', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geovote.age')),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geovote.party')),
            ],
            options={
                'unique_together': {('age', 'party', 'rank')},
            },
        ),
        migrations.CreateModel(
            name='PartyStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_count', models.PositiveIntegerField(default=0)),
                ('support_ratio', models.FloatField(default=0)),
                ('oppose_ratio', models.FloatField(default=0)),
                ('abstain_ratio', models.FloatField(default=0)),
                ('absent_ratio', models.FloatField(default=0)),
                ('total_votes', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('age', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geovote.age')),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geovote.party')),
            ],
            options={
                'verbose_name': '정당별 표결 요약',
                'verbose_name_plural': '정당별 표결 요약들',
                'indexes': [models.Index(fields=['age', 'party'], name='main_partys_age_id_0adde9_idx')],
                'unique_together': {('age', 'party')},
            },
        ),
    ]
