# Generated by Django 5.2.1 on 2025-06-11 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agestats',
            name='enp',
            field=models.FloatField(default=0.0),
        ),
    ]
