# Generated by Django 5.2.1 on 2025-06-09 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clusterkeyword',
            name='cluster_num',
            field=models.IntegerField(),
        ),
    ]
