# Generated by Django 5.2.1 on 2025-06-10 01:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geovote', '0001_initial'),
        ('main', '0002_alter_clusterkeyword_cluster_num'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartyClusterStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cluster_num', models.IntegerField()),
                ('cluster_keyword', models.JSONField(blank=True, null=True)),
                ('support_ratio', models.FloatField(default=0)),
                ('oppose_ratio', models.FloatField(default=0)),
                ('abstain_ratio', models.FloatField(default=0)),
                ('absent_ratio', models.FloatField(default=0)),
                ('total_votes', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': '정당-클러스터 투표 요약',
                'verbose_name_plural': '정당-클러스터 투표 요약들',
            },
        ),
        migrations.RenameModel(
            old_name='AgeSummary',
            new_name='AgeStats',
        ),
        migrations.RenameModel(
            old_name='PartyVoteSummary',
            new_name='PartyStats',
        ),
        migrations.AlterUniqueTogether(
            name='partyclustervotesummary',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='partyclustervotesummary',
            name='age',
        ),
        migrations.RemoveField(
            model_name='partyclustervotesummary',
            name='party',
        ),
        migrations.AddIndex(
            model_name='partystats',
            index=models.Index(fields=['age', 'party'], name='main_partys_age_id_0adde9_idx'),
        ),
        migrations.AddField(
            model_name='partyclusterstats',
            name='age',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geovote.age'),
        ),
        migrations.AddField(
            model_name='partyclusterstats',
            name='party',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geovote.party'),
        ),
        migrations.DeleteModel(
            name='PartyClusterVoteSummary',
        ),
        migrations.AddIndex(
            model_name='partyclusterstats',
            index=models.Index(fields=['age', 'cluster_num', 'party'], name='main_partyc_age_id_5186cd_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='partyclusterstats',
            unique_together={('age', 'cluster_num', 'party')},
        ),
    ]
