# Generated by Django 5.2.1 on 2025-06-10 03:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geovote', '0001_initial'),
        ('main', '0003_partyclusterstats_rename_agesummary_agestats_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartyConcentration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.PositiveSmallIntegerField()),
                ('member_count', models.PositiveIntegerField(default=0)),
                ('vote_support_ratio', models.FloatField(default=0.0)),
                ('age', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geovote.age')),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geovote.party')),
            ],
            options={
                'unique_together': {('age', 'party', 'rank')},
            },
        ),
    ]
