# Generated by Django 5.2.1 on 2025-05-30 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('bill_id', models.CharField(max_length=100, unique=True)),
                ('bill_number', models.CharField(max_length=100, unique=True)),
                ('summary', models.TextField(blank=True, null=True)),
                ('cluster', models.IntegerField(max_length=10, unique=True)),
                ('cluster_keword', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
