# Generated by Django 5.2.1 on 2025-06-26 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('bill_id', models.CharField(max_length=100, unique=True)),
                ('bill_number', models.CharField(max_length=100, unique=True)),
                ('cleaned', models.TextField(blank=True, null=True)),
                ('summary', models.TextField(blank=True, null=True)),
                ('cluster', models.IntegerField()),
                ('cluster_keyword', models.TextField(blank=True, default='', null=True)),
                ('label', models.IntegerField(blank=True, null=True)),
                ('url', models.TextField(blank=True, null=True, unique=True)),
                ('card_news_content', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
