# Generated by Django 5.2.1 on 2025-06-05 00:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billview', '0001_initial'),
        ('geovote', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='age',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geovote.age'),
        ),
    ]
