# Generated by Django 5.2.1 on 2025-06-16 01:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billview', '0001_initial'),
        ('geovote', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='age',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geovote.age'),
        ),
        migrations.AddIndex(
            model_name='bill',
            index=models.Index(fields=['label', 'bill_number'], name='billview_bi_label_f99dc2_idx'),
        ),
        migrations.AddIndex(
            model_name='bill',
            index=models.Index(fields=['cluster_keyword'], name='billview_bi_cluster_5fb060_idx'),
        ),
    ]
