# Generated by Django 5.2.1 on 2025-06-04 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billview", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="bill",
            name="label",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
