# Generated by Django 5.2.1 on 2025-06-12 02:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billview', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='cleaned',
        ),
    ]
