# Generated by Django 5.2.1 on 2025-06-10 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billview', '0003_bill_billview_bi_label_f99dc2_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='created_at',
        ),
        migrations.AddField(
            model_name='bill',
            name='cleaned',
            field=models.TextField(blank=True, null=True),
        ),
    ]
