# Generated by Django 5.2.1 on 2025-06-04 05:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billview", "0003_bill_label"),
    ]

    operations = [
        migrations.AddField(
            model_name="bill",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
